// Pruebas (sin DOM) de los jokers: puntuación, huecos, venta, tienda, recompensas y escalado. Uso: node tools/test-jokers.mjs
import assert from 'node:assert/strict';
import { gs, replaceState } from '../src/state.js';
import { makeCard } from '../src/cards.js';
import * as C from '../src/combat.js';
import * as E from '../src/effects.js';
import { JOKERS, JOKER_IDS, MAX_JOKERS, jokerSellPrice, onRoundWon, pickJoker } from '../src/jokers.js';
import { RNG } from '../src/rng.js';

let ok = 0, bad = 0;
const T = (name, fn) => { try { fn(); ok++; console.log('  ok  ' + name); } catch (e) { bad++; console.log('  FAIL ' + name + '\n       ' + String(e.message).split('\n').slice(0, 3).join(' | ')); } };
const mk = (...ids) => ids.map(i => makeCard(i));
function fresh(jokers = []) { replaceState({}); E.startRun('salon'); gs.jokers = jokers.slice(); gs.jokerData = {}; const R = C.startRound({ key: 't', target: 99999, opp: { id: 'dealer', rule: [] }, tutorial: false }); return R; }
const score = (R, cards, stake = 'none') => C.resolvePlay({ levels: R.levels, mods: R.mods, rule: R.rule, history: R.history, shield: R.shield, deaths: R.deaths, playsLeft: R.playsLeft, jokers: gs.jokers.slice(), jokerData: gs.jokerData, player: { health: gs.player.health, maxHealth: gs.player.maxHealth, sanity: gs.player.sanity, money: gs.player.money, debt: gs.player.debt } }, cards, stake);
const base = (R, cards) => { const j = gs.jokers; gs.jokers = []; const r = score(R, cards); gs.jokers = j; return r; };
const jr = (res, id) => { let r = 1; res.steps.forEach((s, i) => { if (s.j === id && s.t === 'xmult') r *= s.mult / res.steps[i - 1].mult; }); return r; };   // ×Mult que aportó ese comodín

console.log('jokers');
T('hay 19 jokers, todos con precio, rareza y efecto', () => { assert.equal(JOKER_IDS.length, 19); for (const id of JOKER_IDS) { assert.ok(JOKERS[id].price > 0 && ['common', 'uncommon', 'rare'].includes(JOKERS[id].rarity) && typeof JOKERS[id].fx === 'function', id); } });
T('hueco máximo: 5 jokers; el sexto se vende por la mitad', () => { fresh(); const ids = JOKER_IDS.slice(0, 5); for (const id of ids) assert.equal(E.addJoker(id), true); assert.equal(gs.jokers.length, MAX_JOKERS); const m = gs.player.money; assert.equal(E.addJoker('abaco'), false); assert.equal(gs.player.money, m + jokerSellPrice('abaco')); assert.equal(gs.jokers.length, 5); });
T('no se puede tener el mismo joker dos veces', () => { fresh(); assert.equal(E.addJoker('bufon'), true); assert.equal(E.addJoker('bufon'), false); assert.equal(gs.jokers.length, 1); });
T('vender un joker da la mitad de su precio y libera el hueco', () => { fresh(['bufon', 'sonrisa']); const m = gs.player.money; const v = E.sellJoker(0); assert.equal(v, 15); assert.equal(gs.player.money, m + 15); assert.deepEqual(gs.jokers, ['sonrisa']); });
T('El Bufón Mudo: +4 de multiplicador y el paso lleva su id', () => { const R = fresh(['bufon']); const cs = mk('blood_03', 'eye_03', 'key_08'); const a = base(R, cs), b = score(R, cs); assert.equal(b.mult, a.mult + 4); const st = b.steps.filter(s => s.j === 'bufon'); assert.equal(st.length, 1); assert.equal(st[0].t, 'mult'); assert.equal(st[0].v, 4); });
T('La Sonrisa Fija: +30 fichas solo con pareja o mejor', () => { const R = fresh(['sonrisa']); const par = mk('blood_03', 'eye_03', 'key_08'), alta = mk('blood_03', 'eye_07', 'key_08'); assert.equal(score(R, par).chips, base(R, par).chips + 30); assert.equal(score(R, alta).chips, base(R, alta).chips); });
T('La Sanguijuela: +2 mult por cada Sangre que puntúa', () => { const R = fresh(['sanguijuela']); const cs = mk('blood_09', 'blood_04', 'eye_09'); assert.equal(score(R, cs).mult, base(R, cs).mult + 2 * 1); const c2 = mk('blood_09', 'blood_04', 'blood_02', 'blood_07', 'blood_11'); assert.equal(score(R, c2).mult, base(R, c2).mult + 2 * 5); });
T('La Monja Ciega: ×1,25 por figura que puntúa; El As en la Manga: ×1,5 por As', () => { let R = fresh(['monja_ciega']); const cs = mk('blood_11', 'eye_11', 'key_12', 'tooth_13'); assert.ok(Math.abs(jr(score(R, cs), 'monja_ciega') - 1.25 * 1.25) < 1e-9); R = fresh(['as_manga']); const as = mk('blood_01', 'eye_01', 'key_01'); assert.ok(Math.abs(jr(score(R, as), 'as_manga') - 1.5 ** 3) < 1e-9); });
T('La Última Oportunidad: +10 mult solo con 1 jugada restante', () => { const R = fresh(['ultima_oportunidad']); const cs = mk('blood_03', 'eye_03'); R.playsLeft = 3; const a = score(R, cs).mult - base(R, cs).mult; R.playsLeft = 1; const b = score(R, cs).mult - base(R, cs).mult; assert.equal(a, 0); assert.equal(b, 10); });
T('El Trapero: +1 mult por cada 40 de Deuda (máx. +10)', () => { const R = fresh(['trapero']); const cs = mk('blood_03', 'eye_03'); gs.player.debt = 85; assert.equal(score(R, cs).mult - base(R, cs).mult, 2); gs.player.debt = 9999; assert.equal(score(R, cs).mult - base(R, cs).mult, 10); });
T('La Vela de la Viuda (×1,5 con Cordura < 40) y El Último Aliento (×3 con Salud < 30 %)', () => { let R = fresh(['vela_viuda']); const cs = mk('blood_03', 'eye_03'); gs.player.sanity = 70; assert.equal(jr(score(R, cs), 'vela_viuda'), 1); gs.player.sanity = 30; assert.equal(jr(score(R, cs), 'vela_viuda'), 1.5); R = fresh(['ultimo_aliento']); gs.player.health = 50; assert.equal(jr(score(R, cs), 'ultimo_aliento'), 1); gs.player.health = 20; assert.equal(jr(score(R, cs), 'ultimo_aliento'), 3); });
T('Corona Podrida: ×2 con Color o mejor; no con pareja', () => { const R = fresh(['corona_podrida']); const color = mk('blood_01', 'blood_04', 'blood_05', 'blood_09', 'blood_07'), par = mk('blood_03', 'eye_03'); assert.equal(jr(score(R, color), 'corona_podrida'), 2); assert.equal(jr(score(R, par), 'corona_podrida'), 1); });
T('La Casa Siempre Gana: ×1,4 solo si hay apuesta', () => { const R = fresh(['casa_gana']); const cs = mk('blood_03', 'eye_03'); assert.equal(jr(score(R, cs, 'none'), 'casa_gana'), 1); assert.ok(Math.abs(jr(score(R, cs, 'money'), 'casa_gana') - 1.4) < 1e-9); });
T('El Sombrero del Crupier: ×1,3 y cuesta 2 de Cordura por jugada', () => { const R = fresh(['sombrero']); const cs = mk('blood_03', 'eye_03'); const a = score(R, cs), b = base(R, cs); assert.ok(Math.abs(jr(a, 'sombrero') - 1.3) < 1e-9); assert.equal(a.delta.sanity, b.delta.sanity - 2); });
T('El ORDEN importa: +Mult antes de un ×Mult rinde más que después (los comodines actúan de izquierda a derecha)', () => { const cs = mk('eye_01', 'eye_05'); let R = fresh(['bufon', 'as_manga']); const a = score(R, cs); R = fresh(['as_manga', 'bufon']); const b = score(R, cs); assert.ok(a.total > b.total, `${a.total} > ${b.total}`); assert.equal(a.chips, b.chips, 'las fichas no dependen del orden'); const m1 = (1 + 4) * 1.5, m2 = 1 * 1.5 + 4; assert.ok(Math.abs(a.mult * a.xmult - m1) < 1e-9 && Math.abs(b.mult * b.xmult - m2) < 1e-9, `mult ${a.mult * a.xmult} / ${b.mult * b.xmult}`); });
T('El Peaje del Barquero: +2 de Dinero por carta que puntúa', () => { const R = fresh(['peaje']); const cs = mk('blood_03', 'eye_03', 'key_08'); assert.equal(score(R, cs).delta.money, base(R, cs).delta.money + 2 * 2); });
T('El Ábaco Oxidado escala: +1 mult por ronda ganada, y solo si lo tienes', () => { fresh(['abaco']); onRoundWon(gs.jokers, gs.jokerData); onRoundWon(gs.jokers, gs.jokerData); assert.equal(gs.jokerData.abaco, 2); const R = C.startRound({ key: 't2', target: 9999, opp: { id: 'dealer', rule: [] } }); const cs = mk('blood_03', 'eye_03'); assert.equal(score(R, cs).mult - base(R, cs).mult, 2); fresh([]); onRoundWon(gs.jokers, gs.jokerData); assert.equal(gs.jokerData.abaco, undefined); });
T('orden: los jokers puntúan de izquierda a derecha y después de las cartas', () => { const R = fresh(['bufon', 'sonrisa']); const cs = mk('blood_03', 'eye_03', 'key_08'); const st = score(R, cs).steps; const iB = st.findIndex(s => s.j === 'bufon'), iS = st.findIndex(s => s.j === 'sonrisa'), iCard = st.reduce((m, s, k) => (s.i >= 0 ? k : m), -1); assert.ok(iCard < iB && iB < iS, [iCard, iB, iS]); });
T('cada combo anuncia un paso propio (para animarlo)', () => { const R = fresh([]); const cs = mk('eye_03', 'eye_05', 'eye_09', 'eye_11', 'eye_13'); const r = score(R, cs); assert.ok(r.combos.includes('mirada')); assert.ok(r.steps.some(s => s.t === 'combo' && s.id === 'mirada')); });
T('la vista previa y la jugada real coinciden con jokers', () => { const R = fresh(['bufon', 'monja_ciega', 'abaco']); gs.jokerData.abaco = 3; const c = R.hand.slice(0, 3); const pv = C.preview(R, c.map(x => x.uid)); const real = C.play(R, c.map(x => x.uid)); assert.equal(pv.total, real.total); });
T('tienda: ofrece un joker que no tienes y comprarlo respeta dinero y huecos', () => { fresh(['bufon']); let found = null; for (let k = 0; k < 40 && !found; k++) found = E.merchantStock(new RNG(100 + k), 2).find(e => e.kind === 'joker'); assert.ok(found, 'la tienda ofrece jokers'); assert.notEqual(found.id, 'bufon'); gs.player.money = found.price - 1; assert.equal(E.buy(found, new RNG(1)), false); gs.player.money = found.price + 5; assert.equal(E.buy(found, new RNG(1)), true); assert.ok(gs.jokers.includes(found.id)); assert.equal(gs.player.money, 5); });
T('tienda: sin hueco no se puede comprar un joker', () => { fresh(JOKER_IDS.slice(0, 5)); const e = { kind: 'joker', id: JOKER_IDS[8], price: 10 }; gs.player.money = 500; assert.equal(E.buy(e, new RNG(1)), false); assert.equal(gs.player.money, 500); });
T('recompensas: pueden ofrecer joker (nunca uno repetido) y llevárselo', () => { fresh(['bufon']); let j = null; for (let k = 0; k < 80 && !j; k++) j = E.rewardChoices(new RNG(k), 2, false).find(x => x.type === 'joker'); assert.ok(j); assert.notEqual(j.id, 'bufon'); E.takeReward(j); assert.ok(gs.jokers.includes(j.id)); });
T('recompensas de jefe: con hueco libre incluyen un joker (y los demás son objetos)', () => { fresh(); const r = E.rewardChoices(new RNG(7), 7, true); assert.ok(r.some(x => x.type === 'joker')); assert.ok(r.every(x => x.type === 'item' || x.type === 'joker')); });
T('efecto de evento «joker»: da uno al azar, o lo vende si no hay hueco', () => { fresh(); const o = E.applyEffects([['joker', 'random']], { rng: new RNG(3) }); assert.equal(o[0].k, 'joker'); assert.equal(gs.jokers.length, 1); fresh(JOKER_IDS.slice(0, 5)); const m = gs.player.money; const o2 = E.applyEffects([['joker', 'random']], { rng: new RNG(3) }); assert.equal(o2[0].ok, false); assert.ok(gs.player.money > m); });
T('los jokers se reinician al empezar un descenso nuevo', () => { fresh(['bufon', 'abaco']); gs.jokerData.abaco = 4; E.startRun('salon'); assert.deepEqual(gs.jokers, []); assert.deepEqual(gs.jokerData, {}); });
T('pickJoker ignora los que ya tienes y nunca devuelve ids inexistentes', () => { const owned = JOKER_IDS.slice(0, 18); for (let k = 0; k < 20; k++) assert.equal(pickJoker(new RNG(k), owned, 3, false), JOKER_IDS[18]); assert.equal(pickJoker(new RNG(1), JOKER_IDS, 0, false), null); });
console.log(`\n${ok} ok, ${bad} fallos`); process.exit(bad ? 1 : 0);
